
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjmlmhfazplxaxxrghgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qbWxtaGZhenBseGF4eHJnaGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTE1NzksImV4cCI6MjA2MzkyNzU3OX0.5d6uU_g4tAz0b3uuG-AhSAYe-sBATgKHxz-TmoGD7l8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
