// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nypufmfejvnbkezgsuvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cHVmbWZlanZuYmtlemdzdXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODkzNTAsImV4cCI6MjA2NDE2NTM1MH0.V0h3d_4Mz8Sq9c8hzq-vrmEZ0kTYznD2u_NI4DOaOtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);